Blood = {};

Blood.skills = {}; // name : button
Blood.skills["Ravage"] = null; 
Blood.skills["Shadow's Edge"] = null; 
Blood.skills["Spear Flurry"] = null; 
Blood.skills["Wave of Blood"] = null; 
Blood.skills["Tendrils of Blood"] = null; 
Blood.skills["Siphon Blood"] = null; 
Blood.skills["Sanguinate"] = null; 
Blood.skills["Umbral Lance"] = null; 
Blood.skills["Swarm of Bats"] = null; 
Blood.skills["Whirling Strike"] = null; 
Blood.skills["Mephetic Cloud"] = null; 
Blood.skills["Skewer"] = null; 
Blood.skills["Shroud of Night"] = null; 
Blood.skills["Abomination"] = null; 
Blood.skills["Blood Rush"] = null; 
Blood.skills["Shattering Fists"] = null; 
Blood.skills["Transfusion"] = null; 

Blood.terms = {}; // name : button
Blood.terms["aoe"] = null; 
Blood.terms["buff"] = null; 
Blood.terms["burn"] = null; 
Blood.terms["chill"] = null; 
Blood.terms["control"] = null; 
Blood.terms["debuff"] = null; 
Blood.terms["dot"] = null; 
Blood.terms["effectiveness up"] = null; 
Blood.terms["movement"] = null; 
Blood.terms["primary"] = null; 
Blood.terms["selfbuff"] = null; 
Blood.terms["shield"] = null; 
Blood.terms["slow"] = null; 
Blood.terms["speed"] = null; 
Blood.terms["stun"] = null; 
Blood.terms["summon"] = null; 

Blood.essences = {};
Blood.essences["Dereliction"]       = { terms: " debuff slow ", desc: ["Wave of Blood also reduces the Movement Speed of any enemies hit by 40% for 3 seconds."], skill: "Wave of Blood", slot: "Chest" };
Blood.essences["Chiropteran Trade"] = { terms: " effectiveness up ", desc: ["Swarm of Bats damage increased 10%."], skill: "Swarm of Bats", slot: "Chest" };
Blood.essences["Count of the Eves"] = { terms: " selfbuff shield ", desc: ["Whirling Strike also grants 5% damage reduction per enemy hit for 3 seconds. This effect stacks","up to a maximum of 6 times."], skill: "Whirling Strike", slot: "Chest" };
Blood.essences["Influencer"]        = { terms: " summon primary ", desc: ["Shroud of Night now only empowers you, causing every other Primary Attack to conjure a","shadowy apparition to attack enemies."], skill: "Shroud of Night", slot: "Chest" };
Blood.essences["Layered Aims"]      = { terms: " buff primary ", desc: ["Shroud of Night now empowers you and nearby allies, causing your Primary Attacks to mark ","enemies for death. The marks explode upon reaching 5 stacks dealing damage to the marked ","enemy."], skill: "Shroud of Night", slot: "Chest" };
Blood.essences["Momentary Comfort"] = { terms: " buff summon shield ", desc: ["Shroud of Night now periodically conjures shadowy apparitions that grant shields to you and ","nearby allies."], skill: "Shroud of Night", slot: "Chest" };
Blood.essences["No More Bygones"]   = { terms: " debuff ", desc: ["Sanguinate now also shatters enemy armor, increasing the damage they take by 10% for 3 ","seconds."], skill: "Sanguinate", slot: "Chest" };
Blood.essences["Rootvein Mail"]     = { terms: " stun dot ", desc: ["Tendrils of Blood now tethers you to an enemy, Immobilizing you and Stunning them for up to ","3 seconds. The blood tether continually deals damage to the linked enemy and can be broken ","at anytime by activating the skill again."], skill: "Tendrils of Blood", slot: "Chest" };
Blood.essences["Ruin's Bindings"]   = { terms: " stun control ", desc: ["Tendrils of Blood now throws enemies to a targeted location, dealing damage and Stunning them."], skill: "Tendrils of Blood", slot: "Chest" };
Blood.essences["Warmth and Likability"] = { terms: " effectiveness up ", desc: ["Wave of Blood maximum charges increased by 1."], skill: "Wave of Blood", slot: "Chest" };

Blood.essences["Cousin to Wildcats"]    = { terms: " slow aoe stun ", desc: ["Siphon Blood now Slows and binds nearby enemies to you. When Siphon Blood expires you","expel a wave of blood, damaging and Stunning all nearby enemies that were still bound to you."], skill: "Siphon Blood", slot: "Head" };
Blood.essences["Gorger's Yawn"]         = { terms: " effectiveness up ", desc: ["Wave of Blood range increased by 20%."], skill: "Wave of Blood", slot: "Head" };
Blood.essences["Heir of High Regions"]  = { terms: " effectiveness up control ", desc: ["Spear Flurry deals 15% increased damage to enemies suffering loss of control."], skill: "Spear Flurry", slot: "Head" };
Blood.essences["Horns of the Hexed"]    = { terms: " aoe movement ", desc: ["Siphon Blood is no longer Channeled and now moves with you, dealing damage and draining ","the life of nearby enemies."], skill: "Siphon Blood", slot: "Head" };
Blood.essences["Hush"]                  = { terms: " effectiveness up ", desc: ["Shroud of Night's duration increased by 30%."], skill: "Shroud of Night", slot: "Head" };
Blood.essences["Pain is Purpose"]       = { terms: " aoe shield ", desc: ["Siphon Blood now instantly drains the life of nearby enemies to grant yourself or an ally a shield ","that absorbs damage, but it no longer heals you. Shielding an ally will also grant you a shield."], skill: "Siphon Blood", slot: "Head" };
Blood.essences["Siren's Grin"]          = { terms: " effectiveness up ", desc: ["Whirling Strike maximum charges increased by 1."], skill: "Whirling Strike", slot: "Head" };
Blood.essences["Voice of the Crescent"] = { terms: " selfbuff ", desc: ["Shroud of Night also increases your Evasion Rating by 12%."], skill: "Shroud of Night", slot: "Head" };
Blood.essences["Vow of Trickery"]       = { terms: " shield ", desc: ["Whirling Strike also blocks incoming projectiles."], skill: "Whirling Strike", slot: "Head" };
Blood.essences["Wightveil"]             = { terms: " selfbuff aoe debuff ", desc: ["Siphon Blood now absorbs the power from nearby enemies reducing their damage. Each affected ","enemy provides you with increased damage."], skill: "Siphon Blood", slot: "Head" };

Blood.essences["Bardiche of Below"] = { terms: " aoe ", desc: ["Whirling Strike now unleashes a blast, dealing damage to enemies caught in the path."], skill: "Whirling Strike", slot: "Weapon" };
Blood.essences["The Besalver"]      = { terms: " aoe stun ", desc: ["Skewer now causes you to leap into the air and slam into the target location, knocking enemies","up and stunning them."], skill: "Skewer", slot: "Weapon" };
Blood.essences["Blotniffe"]         = { terms: " effectiveness up ", desc: ["Umbral Lance deals up to 20% increased damage, the further you are from the target."], skill: "Umbral Lance", slot: "Weapon" };
Blood.essences["Broken Corseque"]   = { terms: " effectiveness up ", desc: ["When Siphon Blood damages the same enemy 3 times it causes them to hemorrhage, ","dealing additional damage."], skill: "Siphon Blood", slot: "Weapon" };
Blood.essences["Coiled Course"]     = { terms: " aoe ", desc: ["The final strike of the Ravage combo unleashes a wave of energy that deals damage to enemies."], skill: "Ravage", slot: "Weapon" };
Blood.essences["Dire Calling"]      = { terms: " chill slow ", desc: ["Whirling Strike is now infused with frost, Chilling enemies, reducing their Attack and ","Movement Speed."], skill: "Whirling Strike", slot: "Weapon" };
Blood.essences["Red Concord"]       = { terms: " burn ", desc: ["Whirling Strike now combusts, causing enemies to Burn."], skill: "Whirling Strike", slot: "Weapon" };
Blood.essences["Reverent Hunter"]   = { terms: " movement speed debuff slow ", desc: ["Siphon Blood also slows enemy Movement Speed by 30%, absorbing their vigor, and increases ","your Movement Speed by 10%, up to 30%."], skill: "Siphon Blood", slot: "Weapon" };
Blood.essences["Sawtooth"]          = { terms: " movement control ", desc: ["Skewer now causes you to sprint forward while dragging your spear. Release the skill to knock ","your enemy up in the air."], skill: "Skewer", slot: "Weapon" };
Blood.essences["Toothdrinker"]      = { terms: " aoe slow control ", desc: ["Whirling Strike now sweeps your polearm in front of you, damaging, Slowing and pulling enemies ","to the side."], skill: "Whirling Strike", slot: "Weapon" };

Blood.essences["Ageless Cross"]      = { terms: " slow ", desc: [""], skill: "Umbral Lance", slot: "Offhand" };
Blood.essences["Blood Theriac"]      = { terms: " slow ", desc: [""], skill: "Umbral Lance", slot: "Offhand" };
Blood.essences["Hanging Chalice"]    = { terms: " slow ", desc: [""], skill: "Shadow's Edge", slot: "Offhand" };
Blood.essences["Idol of Opulence"]   = { terms: " slow ", desc: [""], skill: "Wave of Blood", slot: "Offhand" };
Blood.essences["Mercy's Plight"]     = { terms: " slow ", desc: [""], skill: "Shadow's Edge", slot: "Offhand" };
Blood.essences["Peer of the Cursed"] = { terms: " slow ", desc: [""], skill: "Wave of Blood", slot: "Offhand" };
Blood.essences["Pinch Point"]        = { terms: " slow ", desc: [""], skill: "Wave of Blood", slot: "Offhand" };
Blood.essences["Sprig of Hawthorn"]  = { terms: " slow ", desc: [""], skill: "Skewer", slot: "Offhand" };
Blood.essences["Wardstone"]          = { terms: " slow ", desc: [""], skill: "Umbral Lance", slot: "Offhand" };
Blood.essences["Woundwell"]          = { terms: " slow ", desc: [""], skill: "Umbral Lance", slot: "Offhand" };

Blood.essences["Castellatia"]           = { terms: " slow ", desc: [""], skill: "Sanguinate", slot: "Pants" };
Blood.essences["Faces of Fading Mirth"] = { terms: " slow ", desc: [""], skill: "Swarm of Bats", slot: "Pants" };
Blood.essences["Journey's End"]         = { terms: " slow ", desc: [""], skill: "Abomination", slot: "Pants" };
Blood.essences["Lianor's Misgivings"]   = { terms: " slow ", desc: [""], skill: "Mephetic Cloud", slot: "Pants" };
Blood.essences["Made to Wander"]        = { terms: " slow ", desc: [""], skill: "Spear Flurry", slot: "Pants" };
Blood.essences["Nightflayer"]           = { terms: " slow ", desc: [""], skill: "Mephetic Cloud", slot: "Pants" };
Blood.essences["Overrun"]               = { terms: " slow ", desc: [""], skill: "Spear Flurry", slot: "Pants" };
Blood.essences["Oversight"]             = { terms: " slow ", desc: [""], skill: "Swarm of Bats", slot: "Pants" };
Blood.essences["Relent Not"]            = { terms: " slow ", desc: [""], skill: "Spear Flurry", slot: "Pants" };
Blood.essences["Reliable Peril"]        = { terms: " slow ", desc: [""], skill: "Abomination", slot: "Pants" };

Blood.essences["Bats and Men Both"]    = { terms: " slow ", desc: [""], skill: "Swarm of Bats", slot: "Shoulder" };
Blood.essences["Bright Arrival"]       = { terms: " slow ", desc: [""], skill: "Abomination", slot: "Shoulder" };
Blood.essences["Consent to Ecstasy"]   = { terms: " slow ", desc: [""], skill: "Abomination", slot: "Shoulder" };
Blood.essences["Dismal Figure"]        = { terms: " slow ", desc: [""], skill: "Mephetic Cloud", slot: "Shoulder" };
Blood.essences["Empress Pariah"]       = { terms: " slow ", desc: [""], skill: "Siphon Blood", slot: "Shoulder" };
Blood.essences["Evil Thoughts"]        = { terms: " slow ", desc: [""], skill: "Umbral Lance", slot: "Shoulder" };
Blood.essences["Fernam's Birthmantle"] = { terms: " slow ", desc: [""], skill: "Spear Flurry", slot: "Shoulder" };
Blood.essences["The Numbing Edge"]     = { terms: " slow ", desc: [""], skill: "Siphon Blood", slot: "Shoulder" };
Blood.essences["Solemn Snare"]         = { terms: " slow ", desc: [""], skill: "Swarm of Bats", slot: "Shoulder" };
Blood.essences["Swarmspeaker"]         = { terms: " slow ", desc: [""], skill: "Swarm of Bats", slot: "Shoulder" };

Game.classes["blood"] = Blood;